Repository Cavonstavant/arcAAAAAAAAAAAAAAAAade, pull requests merged in 2022-04, with the labels that each got.

#74 [*] Updated lib manager to return libs intances
  Src/Core/LibManager.cpp
  Src/Core/LibManager.hpp
Labels: GraphicalLibs, GameLibs

#82 10 graphics libraries ncurses
  Src/CommonInterface/include/IGame.hpp
  Src/CommonInterface/include/IGraph.hpp
  Src/Core/LibManager.cpp
  Src/Core/LibManager.hpp
  Src/GraphicLibs/Ncurses/CMakeLists.txt
  Src/GraphicLibs/Ncurses/NcursesLibrary.cpp
  Src/GraphicLibs/Ncurses/NcursesLibrary.hpp
  Src/GraphicLibs/SDL/SdlLibrary.hpp
  Src/GraphicLibs/SFML/SfmlLibrary.cpp
  Src/GraphicLibs/SFML/SfmlLibrary.hpp
Labels: GraphicalLibs

#92 I graph/adding default window size
  Src/CommonInterface/include/Grid.hpp
  Src/CommonInterface/include/IGame.hpp
  Src/CommonInterface/include/IGraph.hpp
  Src/GraphicLibs/Resources/Font/ARCADE_N.TTF
  Src/GraphicLibs/SFML/SfmlLibrary.cpp
  Src/GraphicLibs/SFML/SfmlLibrary.hpp
Labels: Urgent

#102 Games/nibbler
  Src/CommonInterface/include/IEntity.hpp
  Src/CommonInterface/include/IGame.hpp
  Src/Core/MainMenu/MainMenu.cpp
  Src/Core/MainMenu/MainMenu.hpp
  Src/Games/Common/AEntity.cpp
  Src/Games/Common/AEntity.hpp
Labels: GameLibs

#105 [*] (close #103) Moved initialization of libraries from constructor t…
  Src/CommonInterface/include/IGame.hpp
  Src/CommonInterface/include/IGraph.hpp
  Src/Core/MainMenu/MainMenu.cpp
  Src/Core/MainMenu/MainMenu.hpp
  Src/GraphicLibs/Ncurses/NcursesLibrary.cpp
  Src/GraphicLibs/Ncurses/NcursesLibrary.hpp
  Src/GraphicLibs/SDL/SdlLibrary.cpp
  Src/GraphicLibs/SDL/SdlLibrary.hpp
  Src/GraphicLibs/SFML/SfmlLibrary.cpp
  Src/GraphicLibs/SFML/SfmlLibrary.hpp
Labels: GraphicalLibs

#111 Games/nibbler
  CMakeLists.txt
  Src/Games/Common/AEntity.cpp
  Src/Games/Common/CMakeLists.txt
  Src/Games/Common/Score.cpp
  Src/Games/Common/Score.hpp
  Src/Games/Nibbler/CMakeLists.txt
  Src/Games/Nibbler/Nibbler.cpp
  Src/Games/Nibbler/Nibbler.hpp
  Src/Games/Nibbler/Resources/Font/ARCADE_N.TTF
  Src/Games/Nibbler/Resources/Textures/SnakeHead.png
  Src/Games/Nibbler/Resources/Textures/SnakeTail.png
  Src/Games/Nibbler/entrypoint.cpp
Labels: GameLibs

#116 Core/ungrid
  Src/CommonInterface/include/Grid.hpp
  Src/GraphicLibs/Ncurses/NcursesLibrary.cpp
  Src/GraphicLibs/SDL/EntryPoint.cpp
  Src/GraphicLibs/SDL/SdlLibrary.cpp
Labels: Core, GraphicalLibs

#120 Feature/24 events special core events
  Src/CommonInterface/include/Event.hpp
  Src/CommonInterface/include/IEntity.hpp
  Src/CommonInterface/include/IGame.hpp
  Src/CommonInterface/include/IGraph.hpp
  Src/Core/CMakeLists.txt
  Src/Core/Core.cpp
  Src/Core/Core.hpp
  Src/Core/CoreEvents/CoreEvents.cpp
  Src/Core/EntryPoint.cpp
  Src/Core/Exception.hpp
  Src/Core/LibManager.cpp
  Src/Core/LibManager.hpp
  Src/Core/MainMenu/MainMenu.cpp
  Src/Core/MainMenu/MainMenu.hpp
  Src/Games/CMakeLists.txt
  Src/Games/Common/AEntity.cpp
  Src/Games/Common/AEntity.hpp
  Src/Games/Common/Button.cpp
  Src/Games/Common/CMakeLists.txt
  Src/Games/Common/Enemy.cpp
  Src/Games/Common/Enemy.hpp
  Src/Games/Common/Object.cpp
  Src/Games/Common/Object.hpp
  Src/Games/Common/Player.cpp
  Src/Games/Common/Player.hpp
  Src/Games/Common/Score.cpp
  Src/Games/Common/Score.hpp
  Src/Games/Common/TextEntity.cpp
  Src/Games/Common/TextEntity.hpp
  Src/Games/Nibbler/CMakeLists.txt
  Src/Games/Nibbler/Nibbler.cpp
  Src/Games/Nibbler/Nibbler.hpp
  Src/Games/Nibbler/Resources/Font/ARCADE_N.TTF
  Src/Games/Nibbler/Resources/Textures/Snake/SnakeHead.png
  Src/Games/Nibbler/Resources/Textures/Snake/SnakeTail.png
  Src/Games/Nibbler/entrypoint.cpp
  Src/Games/Pacman/CMakeLists.txt
  Src/Games/Pacman/Pacman.cpp
  Src/Games/Pacman/Pacman.hpp
  Src/Games/Pacman/Resources/map
  Src/Games/Pacman/Resources/textures/enemy.png
  Src/Games/Pacman/Resources/textures/enemySick.png
  Src/Games/Pacman/Resources/textures/pacman.png
  Src/Games/Pacman/entryPoint.cpp
  Src/GraphicLibs/Ncurses/NcursesLibrary.cpp
  Src/GraphicLibs/Ncurses/NcursesLibrary.hpp
  Src/GraphicLibs/SDL/SdlLibrary.cpp
  Src/GraphicLibs/SDL/SdlLibrary.hpp
  Src/GraphicLibs/SFML/SfmlLibrary.cpp
  Src/GraphicLibs/SFML/SfmlLibrary.hpp
  doc/README.pdf
Labels: Core, GraphicalLibs, GameLibs, MainMenu

#108 Feature/58 core
  .gitignore
  .gitkeep
  CMakeLists.txt
  Src/CommonInterface/include/Event.hpp
  Src/CommonInterface/include/Grid.hpp
  Src/CommonInterface/include/IEntity.hpp
  Src/CommonInterface/include/IGame.hpp
  Src/CommonInterface/include/IGraph.hpp
  Src/Core/CMakeLists.txt
  Src/Core/Core.cpp
  Src/Core/Core.hpp
  Src/Core/CoreEvents/CoreEvents.cpp
  Src/Core/EntryPoint.cpp
  Src/Core/Exception.hpp
  Src/Core/LibManager.cpp
  Src/Core/LibManager.hpp
  Src/Core/MainMenu/MainMenu.cpp
  Src/Core/MainMenu/MainMenu.hpp
  Src/Games/CMakeLists.txt
  Src/Games/Common/AEntity.cpp
  Src/Games/Common/AEntity.hpp
  Src/Games/Common/Button.cpp
  Src/Games/Common/Button.hpp
  Src/Games/Common/CMakeLists.txt
  Src/Games/Common/Enemy.cpp
  Src/Games/Common/Enemy.hpp
  Src/Games/Common/Object.cpp
  Src/Games/Common/Object.hpp
  Src/Games/Common/Player.cpp
  Src/Games/Common/Player.hpp
  Src/Games/Common/Score.cpp
  Src/Games/Common/TextEntity.cpp
  Src/Games/Common/TextEntity.hpp
  Src/Games/Nibbler/Nibbler.cpp
  Src/Games/Nibbler/Nibbler.hpp
  Src/Games/Nibbler/Resources/Textures/Snake/SnakeHead.png
  Src/Games/Nibbler/Resources/Textures/Snake/SnakeTail.png
  Src/Games/Pacman/CMakeLists.txt
  Src/Games/Pacman/Pacman.cpp
  Src/Games/Pacman/Pacman.hpp
  Src/Games/Pacman/Resources/map
  Src/Games/Pacman/Resources/textures/enemy.png
  Src/Games/Pacman/Resources/textures/enemySick.png
  Src/Games/Pacman/Resources/textures/pacman.png
  Src/Games/Pacman/entryPoint.cpp
  Src/GraphicLibs/Ncurses/CMakeLists.txt
  Src/GraphicLibs/Ncurses/EntryPoint.cpp
  Src/GraphicLibs/Ncurses/NcursesLibrary.cpp
  Src/GraphicLibs/Ncurses/NcursesLibrary.hpp
  Src/GraphicLibs/SDL/CMakeLists.txt
  Src/GraphicLibs/SDL/EntryPoint.cpp
  Src/GraphicLibs/SDL/SdlLibrary.cpp
  Src/GraphicLibs/SDL/SdlLibrary.hpp
  Src/GraphicLibs/SDL/entrypoint.cpp
  Src/GraphicLibs/SFML/CMakeLists.txt
  Src/GraphicLibs/SFML/EntryPoint.cpp
  Src/GraphicLibs/SFML/SfmlLibrary.cpp
  Src/GraphicLibs/SFML/SfmlLibrary.hpp
  Src/GraphicLibs/SFML/entrypoint.cpp
  doc/README.pdf
Labels: Core, GraphicalLibs, CMake, GameLibs, MainMenu

#143 Feature/140 add missing documentation
  README.md
  Src/Core/Core.cpp
  Src/Core/Core.hpp
  Src/Core/CoreEvents/CoreEvents.cpp
  Src/Core/LibManager.cpp
  Src/Core/LibManager.hpp
  Src/Games/Nibbler/entrypoint.cpp
  Src/Games/Pacman/CMakeLists.txt
  Src/Games/Pacman/Pacman.cpp
  Src/Games/Pacman/entryPoint.cpp
Labels: documentation, Urgent, Core, GraphicalLibs, GameLibs, MainMenu
